# Site settings
title: Merve Sarac
subtitle: Quantitative Methods Researcher
email: sarac (at) wisc (dot) edu
description: MY PERSONAL PAGE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Merve Sarac
street_address: 1025 West Johnson St.
city: Madison
state: WI
zip_code: 53706
country: United States of America
phone:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/saracmrv
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/mrvsarac/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/saracmrv

# Build settings
markdown: kramdown
