# Site settings
title: Merve Sarac
subtitle: Psychometrician | Quantitative Researcher
email: msarac (at) collegeboard (dot) org
description: MY PERSONAL PAGE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Merve Sarac
street_address: 250 Vesey Street
city: New York
state: NY
zip_code: 10281
country: United States of America
phone:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/saracmrv
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/mrvsarac/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/saracmrv
scholar_url: https://scholar.google.com/citations?user=-x9AR-QAAAAJ&hl=en&oi=ao
orcid_url: https://orcid.org/0000-0003-2791-7129

# Build settings
markdown: kramdown
